- name: create the 'adminuser' user
  user: name=adminuser append=yes state=present createhome=yes shell=/bin/bash

- name: allow 'adminuser' to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    line: 'adminuser ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
    
- name: set up authorized keys for the adminuser user
  authorized_key: user=adminuser key="{{item}}"
  with_file:
  - ~/.ssh/id_rsa.pub
