apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-cr
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs: ["*"] #toate actiunile/verbs sunt permise (get,list,create,update,delete) 
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulset
  verbs:
  - get
  - list
