apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap-file
data:
  mysql.conf: |
    [mysqld] # name of file ( key:value and filename:file contents)
    port=3306
    socket=/tmp/mysql.sock
    key_buffer_size=16M
    max_allowed_packet=128M
  
