apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  hostPath:
    path: "/mnt/data" #on local machine storage path (storage backend)
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce