apiVersion: v1
kind: Service
metadata:
  name: sampleapp
  namespace: dev-cluster
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal
spec:
  type: LoadBalancer
  loadBalancerIP: 20.16.183.176
  loadBalancerSourceRanges:
  - 20.16.183.176/24
  selector:
    app: sampleapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080