apiVersion: v1
kind: Service
metadata:
  labels:
    app: sampleapp
  name: sampleapp
  namespace: dev-cluster
spec:
  ports:
  - name: helloworld
    nodePort: 30423
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sampleapp
  sessionAffinity: None
  type: NodePort